### ISSUE TITLE
Make a one-pager ~= landing page

### ISSUE THREAD

**Issue by chadwhitacre** [getsentry/osspledge.com#9]
To aid with #5 we want to spruce up the osspledge.com landing page and produce a one-page PDF for easy email sharing with corporate decision makers.

# [OSS Pledge.pdf](https://github.com/user-attachments/files/16256155/OSS.Pledge.pdf)

**Comment by chadwhitacre** [comment]
Landing page: check.

One-pager still in process.

<img width="1136" alt="Screenshot 2024-07-15 at 9 44 31 PM" src="https://github.com/user-attachments/assets/db8e5f06-fdb7-4cd9-8a16-8cb842f41314">

**Comment by chadwhitacre** [comment]
Current status of the one-pager: [OSS Pledge - DRAFT 1.pdf](https://github.com/user-attachments/files/16249791/OSS.Pledge.-.DRAFT.1.pdf).

**Note:** this is a stop-gap design, _not_ the final design of the full campaign. Due to our time constraints we need to recruit launch pledgers in parallel with baking the final design.

**Comment by vladh** [comment]
I like the brevity! I am a bit concerned about the “we all know…” wording, because it might risk confusing or alienating people who are not fully familiar with what is being referred to. And in any case, restating the motivation might be good.

Just as an example sketch of what I mean:

> Our companies depend on Open Source software — let's make sure we also contribute to keeping the open source ecosystem healthy by paying maintainers fairly. OSS Pledge is a consortium of companies who pay $2000 per year per full-time employed developer back to the Open Source projects they depend on.
> 
> By doing so, we make sure maintainers can maintain their Open Source projects without being overworked, while helping prevent serious security issues like those faced by XZ, Log4j and OpenSSH.
> 
> We care about keeping the software we depend on healthy and about supporting those who build it. Will you join us?

**Comment by chadwhitacre** [comment]
> people who are not fully familiar with what is being referred to

They're unlikely to be good candidates for launch partners, tbh. My thought would be that we can use different positioning on the website itself and materials we develop in the coming months to help recruit the early majority. This is for early adopters.

**Comment by chadwhitacre** [comment]
Final draft of the one-pager: [OSS Pledge - DRAFT 3.pdf](https://github.com/user-attachments/files/16254870/OSS.Pledge.-.DRAFT.3.pdf)

Waiting on new markup to bring the landing page in line, then will call this final.

**Comment by chadwhitacre** [comment]
Here's the final: [OSS Pledge.pdf](https://github.com/user-attachments/files/16256156/OSS.Pledge.pdf). Also linked in the ticket description. Website updated in 9270254b48811abdee2f0b535473c033470bc313. Closing!
